name: fastapi_heroku_pr
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.8
  - dvc-s3
  - numpy
  - pandas=1.2
  - scikit-learn
  - pytest
  - requests
  - uvicorn
  - gunicorn
  - jupyterlab
  - pip: 
      - fastapi==0.63.0
      - pandas-profiling==2.8.0